services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.2/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql

  mysql:  // choose any name you prefer
    image: mysql:8.0 // choose any tag you need
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}  // from .env file
      - MYSQL_USER=${DB_USERNAME}  // from .env file
      - MYSQL_PASSWORD=${DB_PASSWORD}  // from .env file
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}  // from .env file
    volumes:
      - db-data:/var/lib/mysql

networks:
  sail:
    driver: bridge

volumes:
  db-data:
    driver: local
